services:
  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME:-cantian}-nginx
    restart: unless-stopped
    ports:
      - '${HTTP_PORT:-80}:80'
      - '${HTTPS_PORT:-443}:443'
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    networks:
      - web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  web-network:
    driver: bridge
