version: '3.8'

services:
  cantian-app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        BUILD_ENV: ${BUILD_ENV:-sandbox}
    container_name: ${COMPOSE_PROJECT_NAME:-cantian}-app
    restart: unless-stopped
    ports:
      - '${HTTP_PORT:-80}:80'
      - '${HTTPS_PORT:-443}:443'
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    networks:
      - web-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  web-network:
    driver: bridge
