name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 安装依赖并构建
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 删除远程 /workspace/dist 目录所有内容，避免残留旧文件
      - name: Clean remote /workspace/dist directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /workspace/dist/*

      # 上传本地 dist 目录下的所有文件和文件夹到远程 /workspace/dist
      - name: Upload dist contents to remote /workspace/dist
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'dist/*'
          target: '/workspace/dist'

      # 重启 nginx 使改动生效
      - name: Restart nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            systemctl restart nginx
