name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v2

      - name: 安装依赖 & 构建
        run: |
          npm install
          npm run build

      # 删除服务器上 /workspace/dist 目录下所有文件，保证完全替换
      - name: 清空服务器 /workspace/dist 目录内容
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /workspace/dist/*

      # 上传本地 dist 目录所有文件到服务器 /workspace/dist
      - name: 上传 dist 目录到服务器 /workspace/dist
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'dist/*'
          target: '/workspace/dist'

      # 重启 nginx
      - name: 重启 Nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            systemctl restart nginx
