jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉代码
        uses: actions/checkout@v2
      - name: 安装依赖 & 构建
        run: |
          npm install
          npm run build
      - name: 打包 dist 目录
        run: |
          tar -czf dist.tar.gz -C dist .
      - name: 上传压缩包到服务器
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'dist.tar.gz'
          target: '/workspace'
      - name: 服务器解压并清理旧文件
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /workspace/dist
            mkdir -p /workspace/dist
            tar -xzf /workspace/dist.tar.gz -C /workspace/dist
            rm -f /workspace/dist.tar.gz
      - name: 重启 Nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            systemctl restart nginx
