// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BarEcharts: typeof import('./../components/BarEcharts.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    InfiElTable: typeof import('./../components/InfiElTable.vue')['default']
    LeftProgressbar: typeof import('./../components/leftProgressbar.vue')['default']
    LineEcharts: typeof import('./../components/LineEcharts.vue')['default']
    MyCarousel: typeof import('./../components/MyCarousel.vue')['default']
    RightProgressbar: typeof import('./../components/rightProgressbar.vue')['default']
    SingleTable: typeof import('./../components/singleTable.vue')['default']
    VopPlayer: typeof import('./../components/animate/VopPlayer.vue')['default']
  }
}

export { }
