// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CommHeader: typeof import('./components/layout/CommHeader.vue')['default']
    CommonFooter: typeof import('./components/layout/CommonFooter.vue')['default']
    ErrorSvg: typeof import('./components/ErrorSvg.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    SliderCheck: typeof import('./components/SliderCheck.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    TopCenterBottom: typeof import('./components/layout/TopCenterBottom.vue')['default']
  }
}

export { }
