name: Docker Build and Deploy

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: cantian-app
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_ENV=sandbox
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 部署到服务器
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 创建项目目录
            mkdir -p /opt/cantian
            cd /opt/cantian
            
            # 创建 .env 文件
            cat > .env << EOF
            BUILD_ENV=sandbox
            COMPOSE_PROJECT_NAME=cantian
            HTTP_PORT=80
            HTTPS_PORT=443
            TZ=Asia/Shanghai
            IMAGE_TAG=latest
            EOF
            
            # 创建 docker-compose.prod.yml
            cat > docker-compose.prod.yml << 'EOF'
            version: '3.8'
            
            services:
              cantian-app:
                image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
                container_name: \${COMPOSE_PROJECT_NAME:-cantian}-app
                restart: unless-stopped
                ports:
                  - '\${HTTP_PORT:-80}:80'
                  - '\${HTTPS_PORT:-443}:443'
                volumes:
                  - ./logs:/var/log/nginx
                environment:
                  - TZ=\${TZ:-Asia/Shanghai}
                networks:
                  - web-network
                healthcheck:
                  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
                  start_period: 30s
            
            networks:
              web-network:
                driver: bridge
            EOF
            
            # 登录到 Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            
            # 拉取最新镜像并重启服务
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            
            # 清理旧镜像
            docker image prune -f
            
            # 检查服务状态
            docker compose -f docker-compose.prod.yml ps