name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装依赖 & 构建 sandbox
        run: |
          pnpm install
          pnpm run build:sandbox

      - name: 上传构建产物到服务器
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/workspace/dist"

      - name: 重启服务器上的应用
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /workspace
            # 如果使用 Docker 部署
            if [ -f docker-compose.yml ] || [ -f docker-compose.prod.yml ]; then
              echo "使用 Docker 重启服务..."
              docker compose -f docker-compose.prod.yml down 2>/dev/null || docker-compose -f docker-compose.prod.yml down 2>/dev/null || true
              docker compose -f docker-compose.prod.yml up -d 2>/dev/null || docker-compose -f docker-compose.prod.yml up -d 2>/dev/null || true
            # 如果使用 Nginx 直接部署
            elif command -v nginx >/dev/null 2>&1; then
              echo "重启 Nginx 服务..."
              systemctl restart nginx || service nginx restart
            else
              echo "未找到部署方式，请检查服务器配置"
            fi
